name: Deploy Cloud Function V2

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - name: ‚¨áÔ∏è Checkout repository
        uses: actions/checkout@v4

      - name: üîë Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Use the secret created earlier

      - name: 'Set up Cloud SDK'
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v4
        with:
          name: helloWorld
          runtime: nodejs22
          entry_point: helloHttp
          region: us-west1
          environment: GEN_2
